require("dotenv").config?.();
const express=require("express"),path=require("path"),crypto=require("crypto"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),cookieParser=require("cookie-parser");
const {Pool}=require("pg");
const PORT=Number(process.env.PORT||3000);
if(!process.env.DATABASE_URL)throw Error("DATABASE_URL não definida");
if(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32)throw Error("JWT_SECRET deve ter 32+ caracteres");
if(!process.env.ADMIN_PASSWORD||process.env.ADMIN_PASSWORD.length<8)throw Error("ADMIN_PASSWORD deve ter 8+ caracteres");
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==="false"?false:{rejectUnauthorized:false}});
const app=express();app.disable("x-powered-by");app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:"100kb"}));app.use(cookieParser());app.use(rateLimit({windowMs:15*60*1000,limit:300}));
const id=()=>crypto.randomUUID(),clean=v=>String(v??"").trim().replace(/\s+/g," "),key=v=>clean(v).toLowerCase();
const q=async(t,p=[])=>{let r=await pool.query(t,p);return r.rows};
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id UUID PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('ADMIN','SUBADMIN')),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS records(id UUID PRIMARY KEY,name TEXT NOT NULL,cad TEXT NOT NULL UNIQUE,matricula TEXT NOT NULL UNIQUE,serie TEXT NOT NULL,owner_id UUID NOT NULL REFERENCES users(id),status TEXT NOT NULL CHECK(status IN('EM_ANALISE','EFETIVADO','REJEITADO')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),reviewed_at TIMESTAMPTZ,reviewed_by UUID REFERENCES users(id));
CREATE TABLE IF NOT EXISTS audit_log(id BIGSERIAL PRIMARY KEY,actor_id UUID REFERENCES users(id),action TEXT NOT NULL,target_id UUID,details TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_records_owner ON records(owner_id);`);
let a=await q("SELECT id FROM users WHERE email=$1",[key(process.env.ADMIN_EMAIL)]);if(!a.length)await q("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,$2,$3,$4,'ADMIN')",[id(),"Administrador Geral",key(process.env.ADMIN_EMAIL),await bcrypt.hash(process.env.ADMIN_PASSWORD,12)])}
const sign=u=>jwt.sign({sub:u.id,role:u.role},process.env.JWT_SECRET,{expiresIn:"8h"});
async function auth(req,res,next){try{let t=req.cookies.lk_token;if(!t)return res.status(401).json({error:"Não autenticado"});let p=jwt.verify(t,process.env.JWT_SECRET),r=await q("SELECT id,name,email,role,active FROM users WHERE id=$1",[p.sub]);if(!r[0]||!r[0].active)return res.status(401).json({error:"Sessão inválida"});req.user=r[0];next()}catch{res.status(401).json({error:"Não autenticado"})}}
const admin=(req,res,next)=>req.user.role==="ADMIN"?next():res.status(403).json({error:"Acesso restrito ao administrador geral"});
async function audit(a,ac,t,d){await q("INSERT INTO audit_log(actor_id,action,target_id,details) VALUES($1,$2,$3,$4)",[a,ac,t,d||null])}
app.post("/api/login",async(req,res)=>{let e=key(req.body.email),p=String(req.body.password||""),u=(await q("SELECT * FROM users WHERE email=$1",[e]))[0];if(!u||!u.active||!(await bcrypt.compare(p,u.password_hash)))return res.status(401).json({error:"E-mail ou senha inválidos"});res.cookie("lk_token",sign(u),{httpOnly:true,sameSite:"lax",secure:process.env.COOKIE_SECURE==="true",maxAge:28800000});res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post("/api/logout",(req,res)=>{res.clearCookie("lk_token");res.json({ok:true})});
app.get("/api/me",auth,(req,res)=>res.json({user:req.user}));
app.get("/api/dashboard",auth,async(req,res)=>{let w=req.user.role==="ADMIN"?"":"WHERE owner_id=$1",p=req.user.role==="ADMIN"?[]:[req.user.id];let total=(await q(`SELECT COUNT(*)::int c FROM records ${w}`,p))[0].c,pending=(await q(`SELECT COUNT(*)::int c FROM records ${w}${w?" AND":"WHERE"} status='EM_ANALISE'`,p))[0].c,effective=(await q(`SELECT COUNT(*)::int c FROM records ${w}${w?" AND":"WHERE"} status='EFETIVADO'`,p))[0].c,rejected=(await q(`SELECT COUNT(*)::int c FROM records ${w}${w?" AND":"WHERE"} status='REJEITADO'`,p))[0].c,subs=req.user.role==="ADMIN"?(await q("SELECT COUNT(*)::int c FROM users WHERE role='SUBADMIN' AND active=true"))[0].c:0;res.json({total,pending,effective,rejected,subs})});
app.get("/api/users",auth,admin,async(req,res)=>res.json(await q(`SELECT u.id,u.name,u.email,u.active,(SELECT COUNT(*)::int FROM records r WHERE r.owner_id=u.id) record_count FROM users u WHERE u.role='SUBADMIN' ORDER BY u.created_at DESC`)));
app.post("/api/users",auth,admin,async(req,res)=>{let n=clean(req.body.name),e=key(req.body.email),p=String(req.body.password||"");if(!n||!e||p.length<8)return res.status(400).json({error:"Nome, e-mail e senha (mínimo 8 caracteres) são obrigatórios"});try{let u=id();await q("INSERT INTO users(id,name,email,password_hash,role) VALUES($1,$2,$3,$4,'SUBADMIN')",[u,n,e,await bcrypt.hash(p,12)]);await audit(req.user.id,"CRIAR_SUBADMIN",u,n);res.status(201).json({id:u,name:n,email:e,access_path:"/?subadmin="+u})}catch(x){if(x.code==="23505")return res.status(409).json({error:"Este e-mail já está cadastrado"});throw x}});
app.patch("/api/users/:id/active",auth,admin,async(req,res)=>{let r=(await q("SELECT id,name FROM users WHERE id=$1 AND role='SUBADMIN'",[req.params.id]))[0];if(!r)return res.status(404).json({error:"Não encontrado"});await q("UPDATE users SET active=$1 WHERE id=$2",[!!req.body.active,r.id]);await audit(req.user.id,req.body.active?"ATIVAR_SUBADMIN":"DESATIVAR_SUBADMIN",r.id,r.name);res.json({ok:true})});
app.get("/api/records",auth,async(req,res)=>res.json(req.user.role==="ADMIN"?await q("SELECT r.*,u.name owner_name FROM records r JOIN users u ON u.id=r.owner_id ORDER BY r.created_at DESC"):await q("SELECT r.*,u.name owner_name FROM records r JOIN users u ON u.id=r.owner_id WHERE r.owner_id=$1 ORDER BY r.created_at DESC",[req.user.id])));
app.post("/api/records",auth,async(req,res)=>{let n=clean(req.body.name),c=clean(req.body.cad),m=clean(req.body.matricula),s=clean(req.body.serie);if(!n||!c||!m||!s)return res.status(400).json({error:"Todos os campos são obrigatórios"});if((await q("SELECT id FROM records WHERE cad=$1 OR matricula=$2",[c,m])).length)return res.status(409).json({error:"DUPLICIDADE",message:"CAD ou matrícula já cadastrado."});try{let r=id();await q("INSERT INTO records(id,name,cad,matricula,serie,owner_id,status) VALUES($1,$2,$3,$4,$5,$6,'EM_ANALISE')",[r,n,c,m,s,req.user.id]);await audit(req.user.id,"CRIAR_CADASTRO",r,n);res.status(201).json({id:r})}catch(x){if(x.code==="23505")return res.status(409).json({error:"DUPLICIDADE",message:"CAD ou matrícula já cadastrado."});throw x}});
app.patch("/api/records/:id/status",auth,admin,async(req,res)=>{let st=req.body.status;if(!["EFETIVADO","REJEITADO"].includes(st))return res.status(400).json({error:"Status inválido"});let r=(await q("SELECT id,name FROM records WHERE id=$1",[req.params.id]))[0];if(!r)return res.status(404).json({error:"Não encontrado"});await q("UPDATE records SET status=$1,reviewed_at=NOW(),reviewed_by=$2 WHERE id=$3",[st,req.user.id,r.id]);await audit(req.user.id,st==="EFETIVADO"?"EFETIVAR_CADASTRO":"REJEITAR_CADASTRO",r.id,r.name);res.json({ok:true})});
app.get("/api/history",auth,admin,async(req,res)=>res.json(await q("SELECT a.*,u.name actor_name FROM audit_log a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT 500")));
app.get("/api/export.csv",auth,admin,async(req,res)=>{let rs=await q("SELECT r.name,r.cad,r.matricula,r.serie,u.name owner_name,r.status,r.created_at FROM records r JOIN users u ON u.id=r.owner_id ORDER BY r.created_at DESC"),e=v=>`"${String(v??"").replace(/"/g,'""')}"`;let c="\ufeffNome;CAD;Matrícula;Série;Subadministrador;Status;Data\n";for(let r of rs)c+=[r.name,r.cad,r.matricula,r.serie,r.owner_name,r.status,r.created_at].map(e).join(";")+"\n";res.setHeader("Content-Type","text/csv;charset=utf-8");res.setHeader("Content-Disposition",'attachment; filename="LKGERENCIAMENTO_cadastros.csv"');res.send(c)});
app.use(express.static(path.join(__dirname,"public")));app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public/index.html")));
init().then(()=>app.listen(PORT,()=>console.log("LKGERENCIAMENTO iniciado"))).catch(e=>{console.error(e);process.exit(1)});
